.TH TURKMAN 1 2025-02-19 GNU 

.SH NAME
turkman \- automatic manpages translator (Turkish).

.SH SYNOPSIS
.B turkman
[\fIoption\fR]
\fIcommand\fR

.SH DESCRIPTION
.B turkman
is a command-line application that automatically translates man pages into Turkish.

.SH OPTIONS

.TP
.BR \-h ", " \-? ", " \-\-help
displays this help information.

.TP
.BR \-trl ", " \-\-trless ", " \-\-yardım ", " \-\-yardim
displays less menu in turkish.It helps Turkish users to understand how they should read manpages. 

.SH AUTHOR
mmapro12 <asia172007@gmail.com>

