.TH TURKMAN 1 2025-02-19 GNU 

.SH NAME
turkman \- automatic manpages translator (Turkish).

.SH SYNOPSIS
.B turkman
[\fIoption\fR]
\fIcommand\fR

.SH DESCRIPTION
.B turkman
is a command-line application that automatically translates man pages into Turkish.

.SH OPTIONS

.TP
.BR \-\-help
displays help page better than this.

.TP
.BR \-\-trhelp
displays this help page in turkish.

.SH INFO 
For more info visit : https://github.com/mmapro12/turkman

.SH AUTHOR
Mohamad Bashir Alnirabani(mmmapro12 on GitHub) <asia172007@gmail.com>

