.TH TURKMAN 1 "2025-06-15" "turkman" "Kullanıcı Komutları"

.SH İSİM

turkman \- Linux komutları için Türkçe man sayfaları

.SH ÖZET

.B turkman

[\fIKOMUT\fR]

.br

.B turkman

[\fISEÇENEKLER\fR]

.SH AÇIKLAMA

.B turkman

Linux komutlarının man sayfalarını Türkçeye çevirir ve kullanıcıların

ana dillerinde sistem dokümantasyonuna erişmesini sağlar.

.PP

Program, çevirileri bulmak için şu sırayı takip eder:

.IP 1. 4

Yerel Türkçe man sayfaları (/usr/share/man/tr/)

.IP 2. 4

Yerel SQLite veritabanı (~/.turkmandb/)

.IP 3. 4

GitHub deposundan çevrimiçi çeviriler

.SH SEÇENEKLER

.TP

.B \-\-help

Yardım mesajını gösterir

.TP

.B version

Sürüm bilgisini gösterir

.TP

.B update

Turkman'ı en güncel sürüme günceller

.TP

.B db init

Yerel veritabanını başlatır

.TP

.B db sync

GitHub'dan çevirileri senkronize eder

.TP

.B uninstall

Turkman'ı sistemden kaldırır

.SH ÖRNEKLER

.TP

.B turkman ls

'ls' komutunun Türkçe man sayfasını gösterir

.TP

.B turkman db sync

Çeviri veritabanını günceller

.TP

.B turkman version

Sürüm bilgisini gösterir

.SH DOSYALAR

.TP

.I ~/.turkmandb/turkman.db

Yerel çeviri veritabanı

.TP

.I /usr/share/man/tr/

Sistem geneli Türkçe man sayfaları

.SH YAZARLAR

mmapro12 <asia172007@gmail.com>

.SH RAPORLAMA

Hataları GitHub'da bildirin: https://github.com/mmapro12/turkman/issues

.SH AYRICA BAKINIZ

.BR man (1),

.BR mandb (8) 
